<?php

/**
 * @file
 * The Disqus Inline Drupal module.
 */

/**
 * Implements hook_help().
 */
function disqus_inline_help($path, $arg) {
  switch ($path) {
  case 'admin/help#disqus_inline':
    $output = '<p>'. t('Uses the <a href="@disqus">Disqus</a> comment system to enhance comments.', array('@disqus' => 'http://disqus.com')) .'</p>';
    $output.= '<h3>'. t('Installation') .'</h3>';
    $output.= '<ol><li>'. t('Register your site information at <a href="http://disqus.com">Disqus</a>') .'</li>';
    $output.= '<li>'. t('In the <a href="@configuration">Disqus configuration</a>, set the domain to what you registered with Disqus, and what node types you would like to have comments', array('@configuration' => url('admin/config/services/disqus'))) .'</li>';
    $output.= '<li>'. t('Visit the <a href="@permissions">permissions</a>, and set which users you would like to have the ability to view Disqus threads (recommended for role)', array('@permissions' => url('admin/people/permissions', array('fragment' => 'module-disqus')))) .'</li></ol>';
    return $output;
  case 'admin/config/services/disqus':
    return '<p>'. t('The following provides the general configuration options for the <a href="@disqus">Disqus</a> comment web service.', array('@disqus' => 'http://disqus.com')) .'</p>';
  }
}

/**
 * Implements hook_permission().
 */
function disqus_inline_permission() {
  return array(
    'administer disqus inline' => array(
      'title' => t('Administer Disqus Inline'),
      'description' => t('Perform administrative actions with Disqus Inline.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function disqus_inline_menu() {
  $items = array();
  $items['admin/config/disqus-inline'] = array(
    'title' => 'Disqus Inline Configuration',
    'description' => 'Provides configuration options for the Disqus Inline comment system.',
    'access arguments' => array('administer disqus inline'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('disqus_inline_admin_settings'),
    'file' => 'disqus_inline.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_node_view().
 */
function disqus_inline_node_view($node, $view_mode) {
  if (isset($node->disqus) && user_access('view disqus comments') && $node->disqus['status'] == 1) {
    switch ($view_mode) {
      case 'full':
drupal_add_css(drupal_get_path('module', 'disqus_inline') . '/css/style.css');
        drupal_add_js(drupal_get_path('module', 'disqus_inline') . '/js/inlineDisqussions.js',array('scope'=>'footer'));
        drupal_add_js(drupal_get_path('module', 'disqus_inline') . '/js/disqus_inline.js',array('scope'=>'footer'));
        
      break;
    }
  }
  else {
    return array();
  }
}


